### ISSUE TITLE
outdated documentation in `paired-differences`

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-longitudinal#3]
I think this must be left over from before we had optional artifact support (the feature table is now optional in this visualizer, this documentation is just out of date): _A feature table artifact is required input, though whether "metric" is derived from the feature table or metadata is optional._

**Comment by nbokulich** [comment]
it looks like I already corrected this — I cannot find this sentence (or any other mention of feature tables as required input) in the current README.
