### ISSUE TITLE
The meaning of Tutorial Data

### ISSUE THREAD

**Issue by elong0527** [qiime2/q2-longitudinal#45]
How could I find the explanation of data in the folder "tutorial_data"?

I have few questions. 

1. I assume ecam-table-taxa.qza contains species level taxa data
2. I assume ecam_map_maturity.txt contains mapping information. 

Question: 
1. What is ecam-table-maturity.qza?

**Comment by thermokarst** [comment]
Hi @elong0527 - please post this on the [QIIME 2 Forum](https://forum.qiime2.org) - that is where we address these kinds of questions. Thanks!
