### ISSUE TITLE
Standard way to import data in Python

### ISSUE THREAD

**Issue by elong0527** [qiime2/q2-longitudinal#46]
I am exploring the way to import taxa and mapping data in python and develop new functions. 

Could you show me a quick example how to import both taxa and mapping file. Then write a function (that follow _utility.py style) to calculate a beta diversity at Week 0?

Below is my code to include taxa information. But I am not sure what will be the standard way to import mapping information in Qiime2 artifact API. 

```python
from qiime2 import Artifact

taxa = Artifact.load("../tutorial_data/ecam-table-taxa.qza")
taxa_df = taxa.view(pd.DataFrame)
```

**Comment by thermokarst** [comment]
Hi @elong0527 - please post this on the [QIIME 2 Forum](https://forum.qiime2.org) - that is where we address these kinds of questions. Thanks!
