### ISSUE TITLE
ENH: new action: `compute-first-differences`

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-longitudinal#58]
Computes first differences (differences in Y between sequential samples across time X)
X   Y   FD
1    1    
2   3   2
3   7   4
4   11  4

Accepts metadata files, [optionally] distance matrix or feature table

Support [value interpolation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html)? Would be easy for series data but not for matrix!

**Comment by ebolyen** [comment]
Just some questions about the output representation:

So this implies that one sample-replicate won't have a values for a given individual/source?

Are there better ways we could represent this source-sample hierarchy? For instance would it make sense to instead have some kind of table that had the source as the sample ID and then first differences as a columns?

```
               t2-t1,     t3-t2,    t4-t3
source1 
source2
```

(I'm not suggesting changing anything in the open PR right now, just wondering if there's a pattern we can pick out that would be useful generally)

**Comment by ebolyen** [comment]
Or is there a new metadata axis here: Samples, Features, and Source?

**Comment by nbokulich** [comment]
Thanks @ebolyen ! Interesting ideas — I see the source axis getting complicated, though, e.g., if there are multiple replicates at two different time points. One possibility is just to average across replicates?

Currently, the expectation is that there are no replicates; if there are, they are either dropped or one is chosen at random, depending on user input.

The current output is just a `pd.Series` that looks like:
```
    Difference
s1    0.01
s2    0.02
s3    0.03
...
```

In the comment above I was not indicating the output, rather how these are calculated (and the key point there is that there is no first difference for baseline, because first differences are calculated between each pair of sequential samples.
