### ISSUE TITLE
new method: `explore_metadata`: plot longitudinal sample metadata categories/values

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-longitudinal#71]
Example and idea provided by @elong0527:

![image](https://user-images.githubusercontent.com/1907564/32304518-fa3483a8-bf3d-11e7-9ad9-b77390710b49.png)

X-axis = time (or other continuous metric)

y-axis = subject ID

points colored by `group` category (should accept categorical or continuous metadata, infer type, and color-code accordingly)

Could also add a parameter to change size or shape of points based on other optional metadata category inputs???

**Comment by jairideout** [comment]
Closing in favor of https://github.com/qiime2/q2-metadata/issues/14
