### ISSUE TITLE
adjust alpha level in linear-mixed-effects scatterplots 

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-longitudinal#74]
**Current Behavior**
issues with glyph overdraw:
![image](https://user-images.githubusercontent.com/1907564/32895715-92da2ef0-caa6-11e7-9187-d0dec8f6ac60.png)

**Comment by cherman2** [comment]
Is this issue relevant?

**Comment by nbokulich** [comment]
no I think we can just close it. It is a "good to have" and would be simple, but this is just a quick diagnostic plot anyway, nothing that would be used for publication.
