### ISSUE TITLE
`volatility`: download SVG

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-longitudinal#89]

**Comment by cherman2** [comment]
<img width="1438" alt="Screenshot 2023-10-26 at 11 41 24 AM" src="https://github.com/qiime2/q2-longitudinal/assets/60228108/5a2907a0-ae12-4f17-85c1-6a1b2fcb8a1c">
It looks like saving as a SVG for volatility is available. I am going to close this. Please re-open if I am mistaken!
