### ISSUE TITLE
statsmodels 0.9.0 appears to break existing tests

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-longitudinal#96]
Should investigate updating tests, pinning `statsmodels`, or some other unconsidered option(s).

**Comment by thermokarst** [comment]
Failing tests on [`busywork`](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-longitudinal/builds/31).

**Comment by nbokulich** [comment]
I think just update the tests. It _looks_ like statsmodels may have made the row names in the summary results more clear, so we should just propagate that.

**Comment by thermokarst** [comment]
Sounds good - we should probably update the conda recipe to pin the minimum version of `statsmodels`.
